version: '3'

services:
  update:
    build: .
    env_file:
      - .env
    networks:
      - mongo
    command: ["spotifystats", "start"]

  rest-api:
    build: .
    stop_signal: SIGINT # Flask requires SIGINT to stop gracefully
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - mongo
    command: ["spotifystats", "run-api"]

networks:
  mongo:
    name: shared-services_mongo
    external: true
