version: '3'

services:
  update:
    image: spotify-stats:dev
    stop_signal: SIGINT # Flask requires SIGINT to stop gracefully
    ports:
      - "5001:5000"
    networks:
      - mongo
    command: ["spotifystats", "start"]

  rest-api:
    image: spotify-stats:dev
    stop_signal: SIGINT # Flask requires SIGINT to stop gracefully
    ports:
      - "5000:5000"
    networks:
      - mongo
    command: ['spotifystats', 'run-api']

networks:
  mongo:
    name: shared-services_mongo
    external: true
