name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  SPOTIFYSTATS_MONGODB_DB_NAME: spotify-stats
  SPOTIFYSTATS_MONGODB_URI: mongodb://localhost:27017/

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
    name: Service tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest
          pip install -r requirements.txt -e .
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
      - name: Run tests
        run: pytest
